//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FilmFree.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Film
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Film()
        {
            this.BildirilenHatalar = new HashSet<BildirilenHatalar>();
            this.IframeTablosu = new HashSet<IframeTablosu>();
            this.Yorumlar = new HashSet<Yorumlar>();
            this.Kullanicilar = new HashSet<Kullanicilar>();
            this.FilmTur = new HashSet<FilmTur>();
            this.anasayfaSlayt = new HashSet<anasayfaSlayt>();
        }
    
        public int id { get; set; }
        public string Isim { get; set; }
        public int SureDK { get; set; }
        public Nullable<System.DateTime> YayınTarihi { get; set; }
        public string ResimYol { get; set; }
        public string Icerik { get; set; }
        public string Oyuncular { get; set; }
        public string Tags { get; set; }
        public int IzlenmeSayisi { get; set; }
        public int YorumSayisi { get; set; }
        public int BegenilmeSayisi { get; set; }
        public Nullable<System.DateTime> eklenmeTarihi { get; set; }
        public string IMDB { get; set; }
        public bool ErisimEngelli { get; set; }
        public string Dil { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BildirilenHatalar> BildirilenHatalar { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<IframeTablosu> IframeTablosu { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Yorumlar> Yorumlar { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Kullanicilar> Kullanicilar { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FilmTur> FilmTur { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<anasayfaSlayt> anasayfaSlayt { get; set; }
    }
}
