//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FilmFree.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class GonderilenMailTipleri
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public GonderilenMailTipleri()
        {
            this.GonderilenMailler = new HashSet<GonderilenMailler>();
        }
    
        public int id { get; set; }
        public string TipAdi { get; set; }
        public int ZamanAsimiSuresiDKCinsi { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GonderilenMailler> GonderilenMailler { get; set; }
    }
}
