//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FilmFree.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class GonderilenMailler
    {
        public int id { get; set; }
        public int KullaniciId { get; set; }
        public int GonderimTipiId { get; set; }
        public System.DateTime GonderimZamani { get; set; }
        public bool IslemGerceklestiMi { get; set; }
        public string token { get; set; }
    
        public virtual GonderilenMailTipleri GonderilenMailTipleri { get; set; }
        public virtual Kullanicilar Kullanicilar { get; set; }
    }
}
