//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FilmFree.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Yorumlar
    {
        public int id { get; set; }
        public int filmId { get; set; }
        public string Ad { get; set; }
        public string Mail { get; set; }
        public string Yorum { get; set; }
        public System.DateTime Tarih { get; set; }
        public bool onayliMi { get; set; }
        public Nullable<int> onaylayanId { get; set; }
        public Nullable<System.DateTime> onaylanmaTarihi { get; set; }
    
        public virtual Film Film { get; set; }
        public virtual Kullanicilar Kullanicilar { get; set; }
    }
}
